version: '3'
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      command: /bin/sh -c "go run main.go"
      stdin_open: true
      tty: true
      ports:   
        - '8080:8080'
      volumes:
        - .:/go/src/MentorApp
      depends_on:
        - "db"

  db:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: wake
        TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6060:6060"
    volumes:
      - ./data/redis:/data
